services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
